package de.lessvoid.coregl;

import java.nio.*;

public interface CoreGL {
	// OpenGL constants
	public int GL_ALPHA();
	public int GL_ALPHA_TEST();
	public int GL_BLEND();
	public int GL_BLEND_DST();
	public int GL_BLEND_SRC();
	public int GL_BYTE();
	public int GL_COLOR_ARRAY();
	public int GL_COLOR_BUFFER_BIT();
	public int GL_CULL_FACE();
	public int GL_DEPTH_TEST();
	public int GL_DST_COLOR();
	public int GL_FALSE();
	public int GL_FLOAT();
	public int GL_INVALID_ENUM();
	public int GL_INVALID_OPERATION();
	public int GL_INVALID_VALUE();
	public int GL_LIGHTING();
	public int GL_LINEAR();
	public int GL_LINEAR_MIPMAP_LINEAR();
	public int GL_LINEAR_MIPMAP_NEAREST();
	public int GL_LUMINANCE();
	public int GL_LUMINANCE_ALPHA();
	public int GL_MAX_TEXTURE_SIZE();
	public int GL_MODELVIEW();
	public int GL_NEAREST();
	public int GL_NEAREST_MIPMAP_LINEAR();
	public int GL_NEAREST_MIPMAP_NEAREST();
	public int GL_NO_ERROR();
	public int GL_NOTEQUAL();
	public int GL_ONE_MINUS_SRC_ALPHA();
	public int GL_OUT_OF_MEMORY();
	public int GL_POINTS();
	public int GL_PROJECTION();
	public int GL_RGB();
	public int GL_RGBA();
	public int GL_SHORT();
	public int GL_SRC_ALPHA();
	public int GL_STACK_OVERFLOW();
	public int GL_STACK_UNDERFLOW();
	public int GL_TEXTURE_2D();
	public int GL_TEXTURE_BINDING_2D();
	public int GL_TEXTURE_COORD_ARRAY();
	public int GL_TEXTURE_MAG_FILTER();
	public int GL_TEXTURE_MIN_FILTER();
	public int GL_TRIANGLES();
	public int GL_TRIANGLE_STRIP();
	public int GL_TRIANGLE_FAN();
	public int GL_TRUE();
	public int GL_UNSIGNED_BYTE();
	public int GL_UNSIGNED_SHORT();
	public int GL_UNSIGNED_SHORT_4_4_4_4();
	public int GL_UNSIGNED_SHORT_5_5_5_1();
	public int GL_UNSIGNED_SHORT_5_6_5();
	public int GL_VERTEX_ARRAY();
	public int GL_VIEWPORT();
	public int GL_ZERO();
	public int GL_ACTIVE_TEXTURE();
	public int GL_ARRAY_BUFFER();
	public int GL_BITMAP();
	public int GL_BGR();
	public int GL_BGRA();
	public int GL_BLUE();
	public int GL_COLOR_INDEX();
	public int GL_COMPILE_STATUS();
	public int GL_COMPRESSED_ALPHA();
	public int GL_COMPRESSED_LUMINANCE();
	public int GL_COMPRESSED_LUMINANCE_ALPHA();
	public int GL_COMPRESSED_RGB();
	public int GL_COMPRESSED_RGBA();
	public int GL_CURRENT_PROGRAM();
	public int GL_DYNAMIC_DRAW();
	public int GL_ELEMENT_ARRAY_BUFFER();
	public int GL_FRAGMENT_SHADER();
	public int GL_GEOMETRY_SHADER();
	public int GL_GREEN();
	public int GL_INT();
	public int GL_LINK_STATUS();
	public int GL_PRIMITIVE_RESTART();
	public int GL_PRIMITIVE_RESTART_INDEX();
	public int GL_RED();
	public int GL_STATIC_DRAW();
	public int GL_STREAM_DRAW();
	public int GL_TEXTURE0();
	public int GL_TEXTURE_CUBE_MAP_NEGATIVE_X();
	public int GL_TEXTURE_CUBE_MAP_NEGATIVE_Y();
	public int GL_TEXTURE_CUBE_MAP_NEGATIVE_Z();
	public int GL_TEXTURE_CUBE_MAP_POSITIVE_X();
	public int GL_TEXTURE_CUBE_MAP_POSITIVE_Y();
	public int GL_TEXTURE_CUBE_MAP_POSITIVE_Z();
	public int GL_UNSIGNED_BYTE_2_3_3_REV();
	public int GL_UNSIGNED_BYTE_3_3_2();
	public int GL_UNSIGNED_INT();
	public int GL_UNSIGNED_INT_10_10_10_2();
	public int GL_UNSIGNED_INT_2_10_10_10_REV();
	public int GL_UNSIGNED_INT_8_8_8_8();
	public int GL_UNSIGNED_INT_8_8_8_8_REV();
	public int GL_UNSIGNED_SHORT_5_6_5_REV();
	public int GL_UNSIGNED_SHORT_4_4_4_4_REV();
	public int GL_UNSIGNED_SHORT_1_5_5_5_REV();
	public int GL_VERTEX_SHADER();
	public int GL_WRITE_ONLY();

	// OpenGL methods
	public void glAlphaFunc (int func, float ref);
	public void glBindTexture (int target, int texture);
	public void glBlendFunc (int sfactor, int dfactor);
	public void glClear (int mask);
	public void glClearColor (float red, float green, float blue, float alpha);
	public void glColorPointer (int size, int type, int stride, FloatBuffer pointer);
	public void glDeleteTextures (int n, IntBuffer textures);
	public void glDisable (int cap);
	public void glDisableClientState (int array);
	public void glDrawArrays (int mode, int first, int count);
	public void glDrawElements(int mode, int count, int type, int indices);
	public void glEnable (int cap);
	public void glEnableClientState (int array);
	public void glGenTextures (int n, IntBuffer textures);
	public int glGetError();
	public void glGetIntegerv (int pname, int[] params, int offset);
	public void glGetIntegerv (int pname, IntBuffer params);
	public boolean glIsEnabled(int cap);
	public void glLoadIdentity();
	public void glMatrixMode (int mode);
	public void glOrthof (float left, float right, float bottom, float top, float zNear, float zFar);
	public void glTexCoordPointer (int size, int type, int stride, FloatBuffer pointer);
	public void glTexImage2D (int target, int level, int internalformat, int width, int height, int border, int format, int type, ByteBuffer pixels);
	public void glTexImage2D (int target, int level, int internalformat, int width, int height, int border, int format, int type, DoubleBuffer pixels);
	public void glTexImage2D (int target, int level, int internalformat, int width, int height, int border, int format, int type, FloatBuffer pixels);
	public void glTexImage2D (int target, int level, int internalformat, int width, int height, int border, int format, int type, IntBuffer pixels);
	public void glTexImage2D (int target, int level, int internalformat, int width, int height, int border, int format, int type, ShortBuffer pixels);
	public void glTexParameterf (int target, int pname, float param);
	public void glTexParameteri(int target, int pname, int param);
	public void glTexSubImage2D (int target, int level, int xoffset, int yoffset, int width, int height, int format, int type, ByteBuffer pixels);
	public void glTranslatef (float x, float y, float z);
	public void glVertexPointer (int size, int type, int stride, FloatBuffer pointer);
	public void glViewport (int x, int y, int width, int height);
	public void glActiveTexture(int texture);
	public void glAttachShader(int program, int shader);
	public void glBindAttribLocation(int program, int index, String name);
	public void glBindBuffer(int target, int buffer);
	public void glBindVertexArray(int array);
	public void glBufferData(int target, IntBuffer data, int usage);
	public void glBufferData(int target, FloatBuffer data, int usage);
	public void glCompileShader(int shader);
	public int glCreateProgram();
	public int glCreateShader(int type);
	public void glDeleteBuffers(int n, IntBuffer buffers);
	public void glDeleteVertexArrays(int n, IntBuffer arrays);
	public void glDrawArraysInstanced(int mode, int first, int count, int primcount);
	public void glEnableVertexAttribArray(int index);
	public void glGenBuffers(int n, IntBuffer buffers);
	public void glGenerateMipmap(int target);
	public void glGenVertexArrays(int n, IntBuffer arrays);
	public int glGetAttribLocation(int program, String name);
	public void glGetProgramiv(int program, int pname, IntBuffer params);
	public String glGetProgramInfoLog(int program);
	public void glGetShaderiv(int shader, int pname, IntBuffer params);
	public String glGetShaderInfoLog(int shader);
	public int glGetUniformLocation(int program, String name);
	public void glLinkProgram(int program);
	public ByteBuffer glMapBuffer(int target, int access, long length, ByteBuffer oldBuffer);
	public void glPrimitiveRestartIndex(int index);
	public void glShaderSource(int shader, String string);
	public void glUniform1(int location, FloatBuffer values);
	public void glUniform1f(int location, float v0);
	public void glUniform2f(int location, float v0, float v1);
	public void glUniform3f(int location, float v0, float v1, float v2);
	public void glUniform4f(int location, float v0, float v1, float v2, float v3);
	public void glUniform1i(int location, int v0);
	public void glUniform2i(int location, int v0, int v1);
	public void glUniform3i(int location, int v0, int v1, int v2);
	public void glUniform4i(int location, int v0, int v1, int v2, int v3);
	public void glUniformMatrix4(int location, boolean transpose, FloatBuffer matrices);
	public boolean glUnmapBuffer(int target);
	public void glUseProgram(int program);
	public void glVertexAttribPointer(int index, int size, int type, boolean normalized, int stride, long offset);
	
	public void checkGLError();
	public void checkGLError(String msg);
	public void checkGLError(String msg, boolean throwException);
	
	public CoreUtil getUtil();
}
